-include ../../../../petscdir.mk
PETSC_DIR=/home/luqs/lib/petsc-3.16.6-opt

CFLAGS           =
CPPFLAGS         =
EXAMPLESC        = main.cpp
MANSEC           = KSP
CLEANFILES       = 
NP               = 1
DIRS             = 

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
